# Generated by Django 3.1.7 on 2021-03-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(blank=True, choices=[('action', 'Action'), ('adventure', 'Adventure'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror')], max_length=10)),
                ('studio', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=150)),
                ('cast', models.CharField(max_length=255)),
                ('collection', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
